### ISSUE TITLE
Multicall for cheaper read-only RPC calls

### ISSUE THREAD

**Issue by spengrah** [Hats-Protocol/sdk-v1-core#1]
Enable the use of multicall (either in-protocol or an external multicall contract) to batch multiple concurrent staticcalls into a single RPC call. This will be both more efficient and and cheaper (in terms of RPC cost) for apps.

Cases where apps may want to do multiple concurrent staticcalls include:
- checking whether a set of addresses are indeed currently wearing a given hat (or a set of hats)
- checking the active status of a set of hats
- checking revert conditions for certain actions like link requests, link approvals, transfers, etc

**Comment by scottrepreneur** [comment]
This is included in the current sdk
