### ISSUE TITLE
HSG sdk

### ISSUE THREAD

**Issue by scottrepreneur** [Hats-Protocol/sdk-v1-core#27]
Repo established:
https://github.com/Hats-Protocol/hsg-sdk

- "core" read and write interactions for HSG
  - `claim`
  - `remove signer`
  - `changeThresholds`
  - `changeOwner`

- Can hold off on any subgraph fetching for now?

**Comment by gershido** [comment]
HSG SDK is ready and published:
https://github.com/Hats-Protocol/hsg-sdk
